<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create sample organizations first
        $organizations = [
            [
                'name' => 'Emirates Red Crescent',
                'slug' => 'emirates-red-crescent',
                'description' => 'The Emirates Red Crescent is a humanitarian organization dedicated to helping those in need across the UAE and internationally.',
                'email' => 'info@emiratesrc.ae',
                'phone' => '+971-2-6651999',
                'website' => 'https://www.emiratesrc.ae',
                'address' => 'Abu Dhabi, UAE',
                'city' => 'Abu Dhabi',
                'emirate' => 'Abu Dhabi',
                'status' => 'approved',
                'is_verified' => true,
                'approved_at' => now(),
                'organization_type' => 'charity',
                'focus_areas' => json_encode(['humanitarian', 'emergency_response', 'community_service']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dubai Cares',
                'slug' => 'dubai-cares',
                'description' => 'Dubai Cares is a UAE-based global philanthropic organization working towards the provision of quality education in developing countries.',
                'email' => 'info@dubaicares.ae',
                'phone' => '+971-4-3640001',
                'website' => 'https://www.dubaicares.ae',
                'address' => 'Dubai, UAE',
                'city' => 'Dubai',
                'emirate' => 'Dubai',
                'status' => 'approved',
                'is_verified' => true,
                'approved_at' => now(),
                'organization_type' => 'charity',
                'focus_areas' => json_encode(['education', 'international_development', 'children']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sharjah Charity International',
                'slug' => 'sharjah-charity-international',
                'description' => 'Sharjah Charity International is committed to humanitarian work and community development.',
                'email' => 'info@sci.ae',
                'phone' => '+971-6-5694999',
                'website' => 'https://www.sci.ae',
                'address' => 'Sharjah, UAE',
                'city' => 'Sharjah',
                'emirate' => 'Sharjah',
                'status' => 'approved',
                'is_verified' => true,
                'approved_at' => now(),
                'organization_type' => 'charity',
                'focus_areas' => json_encode(['humanitarian', 'community_development', 'social_welfare']),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('organizations')->insert($organizations);

        // Get the created organizations
        $orgIds = DB::table('organizations')->pluck('id', 'name');

        // Create sample events
        $events = [
            [
                'title' => 'Beach Cleanup Drive - Dubai Marina',
                'slug' => 'beach-cleanup-drive-dubai-marina',
                'description' => 'Join us for a community beach cleanup at Dubai Marina. Help preserve our beautiful coastline while connecting with fellow environmental enthusiasts.',
                'requirements' => 'Bring water, wear comfortable clothes and closed shoes. Gloves and cleanup materials will be provided.',
                'organization_id' => $orgIds['Emirates Red Crescent'],
                'category' => 'Environment',
                'tags' => json_encode(['environment', 'cleanup', 'beach', 'community']),
                'start_date' => Carbon::now()->addDays(15)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(15)->format('Y-m-d H:i:s'),
                'start_time' => '08:00:00',
                'end_time' => '12:00:00',
                'location' => 'Dubai Marina Beach',
                'address' => 'Dubai Marina Beach, Dubai Marina, Dubai',
                'city' => 'Dubai',
                'emirate' => 'Dubai',
                'max_volunteers' => 50,
                'min_age' => 16,
                'max_age' => null,
                'skills_required' => json_encode(['teamwork', 'physical_fitness']),
                'volunteer_hours' => 4.0,
                'status' => 'published',
                'is_featured' => true,
                'requires_application' => true,
                'application_deadline' => Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
                'contact_person' => 'Ahmed Al Mansouri',
                'contact_email' => 'ahmed@emiratesrc.ae',
                'contact_phone' => '+971-50-1234567',
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Food Distribution for Families in Need',
                'slug' => 'food-distribution-families-need',
                'description' => 'Help distribute food packages to families in need across Dubai. Make a direct impact on community welfare.',
                'requirements' => 'Must be able to lift packages up to 10kg. Transportation will be provided.',
                'organization_id' => $orgIds['Dubai Cares'],
                'category' => 'Community Service',
                'tags' => json_encode(['food', 'charity', 'families', 'community']),
                'start_date' => Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'location' => 'Dubai Community Center',
                'address' => 'Al Karama, Dubai, UAE',
                'city' => 'Dubai',
                'emirate' => 'Dubai',
                'max_volunteers' => 30,
                'min_age' => 18,
                'max_age' => null,
                'skills_required' => json_encode(['communication', 'empathy', 'physical_fitness']),
                'volunteer_hours' => 6.0,
                'status' => 'published',
                'is_featured' => false,
                'requires_application' => true,
                'application_deadline' => Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
                'contact_person' => 'Fatima Al Zahra',
                'contact_email' => 'fatima@dubaicares.ae',
                'contact_phone' => '+971-50-2345678',
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reading Program for Children',
                'slug' => 'reading-program-children',
                'description' => 'Volunteer to read stories and help children develop their literacy skills at local community centers.',
                'requirements' => 'Good communication skills in English and/or Arabic. Background check required.',
                'organization_id' => $orgIds['Sharjah Charity International'],
                'category' => 'Education',
                'tags' => json_encode(['education', 'children', 'reading', 'literacy']),
                'start_date' => Carbon::now()->addDays(20)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(20)->format('Y-m-d H:i:s'),
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'location' => 'Sharjah Public Library',
                'address' => 'Cultural Square, Sharjah, UAE',
                'city' => 'Sharjah',
                'emirate' => 'Sharjah',
                'max_volunteers' => 15,
                'min_age' => 21,
                'max_age' => null,
                'skills_required' => json_encode(['communication', 'patience', 'child_interaction']),
                'volunteer_hours' => 2.0,
                'status' => 'published',
                'is_featured' => true,
                'requires_application' => true,
                'application_deadline' => Carbon::now()->addDays(15)->format('Y-m-d H:i:s'),
                'contact_person' => 'Omar Hassan',
                'contact_email' => 'omar@sci.ae',
                'contact_phone' => '+971-50-3456789',
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Senior Citizens Support Program',
                'slug' => 'senior-citizens-support-program',
                'description' => 'Spend time with elderly residents, assist with activities, and provide companionship at senior care facilities.',
                'requirements' => 'Patience, empathy, and good communication skills. Training will be provided.',
                'organization_id' => $orgIds['Emirates Red Crescent'],
                'category' => 'Healthcare',
                'tags' => json_encode(['elderly', 'healthcare', 'companionship', 'support']),
                'start_date' => Carbon::now()->addDays(12)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(12)->format('Y-m-d H:i:s'),
                'start_time' => '10:00:00',
                'end_time' => '14:00:00',
                'location' => 'Abu Dhabi Senior Care Center',
                'address' => 'Khalifa City, Abu Dhabi, UAE',
                'city' => 'Abu Dhabi',
                'emirate' => 'Abu Dhabi',
                'max_volunteers' => 20,
                'min_age' => 18,
                'max_age' => null,
                'skills_required' => json_encode(['empathy', 'communication', 'patience']),
                'volunteer_hours' => 4.0,
                'status' => 'published',
                'is_featured' => false,
                'requires_application' => true,
                'application_deadline' => Carbon::now()->addDays(7)->format('Y-m-d H:i:s'),
                'contact_person' => 'Aisha Mohammed',
                'contact_email' => 'aisha@emiratesrc.ae',
                'contact_phone' => '+971-50-4567890',
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tree Planting Initiative - Al Ain',
                'slug' => 'tree-planting-initiative-al-ain',
                'description' => 'Join our environmental conservation effort by planting native trees in Al Ain. Help combat climate change and beautify our community.',
                'requirements' => 'Wear old clothes and bring gardening gloves if you have them. Tools and refreshments provided.',
                'organization_id' => $orgIds['Dubai Cares'],
                'category' => 'Environment',
                'tags' => json_encode(['environment', 'trees', 'conservation', 'climate']),
                'start_date' => Carbon::now()->addDays(25)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(25)->format('Y-m-d H:i:s'),
                'start_time' => '07:00:00',
                'end_time' => '11:00:00',
                'location' => 'Al Ain Oasis',
                'address' => 'Al Ain Oasis, Al Ain, UAE',
                'city' => 'Al Ain',
                'emirate' => 'Abu Dhabi',
                'max_volunteers' => 40,
                'min_age' => 16,
                'max_age' => null,
                'skills_required' => json_encode(['physical_fitness', 'environmental_awareness']),
                'volunteer_hours' => 4.0,
                'status' => 'published',
                'is_featured' => true,
                'requires_application' => true,
                'application_deadline' => Carbon::now()->addDays(20)->format('Y-m-d H:i:s'),
                'contact_person' => 'Khalid Al Mansoori',
                'contact_email' => 'khalid@dubaicares.ae',
                'contact_phone' => '+971-50-5678901',
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('events')->insert($events);
    }
}
