<!DOCTYPE html>
<html>
<head>
    <title>{{ $reportData['report_title'] ?? 'Report' }}</title>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        .metrics {
            display: flex;
            flex-wrap: wrap;
            margin: 20px 0;
        }
        .metric {
            flex: 1;
            min-width: 150px;
            padding: 10px;
            margin: 5px;
            border: 1px solid #ddd;
            border-radius: 4px;
            text-align: center;
        }
        .metric-label {
            font-size: 11px;
            color: #666;
            margin-bottom: 5px;
        }
        .metric-value {
            font-size: 16px;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $reportData['report_title'] ?? 'Analytics Report' }}</h1>
        <p>Generated on {{ $generatedAt->format('F j, Y g:i A') }}</p>
    </div>

    @if(isset($reportData['metrics']))
    <div class="metrics">
        @foreach($reportData['metrics'] as $label => $value)
        <div class="metric">
            <div class="metric-label">{{ $label }}</div>
            <div class="metric-value">{{ $value }}</div>
        </div>
        @endforeach
    </div>
    @endif

    @if(isset($reportData['chart_data']))
    <div>
        <h3>Data Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reportData['chart_data']['labels'] as $index => $label)
                <tr>
                    <td>{{ $label }}</td>
                    <td class="text-center">{{ $reportData['chart_data']['values'][$index] ?? 0 }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was generated by SwaedUAE Volunteer Management Platform</p>
        <p>Page 1 of 1</p>
    </div>
</body>
</html>